#index:
#    path: /
#    controller: App\Controller\DefaultController::index

hello_world:
    path: /hello-world
    controller: App\Controller\AdvertController::index

db:
    path: /db
    controller: App\Controller\db::connection
