<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZySl4D4\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZySl4D4/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZySl4D4.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZySl4D4\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerZySl4D4\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'ZySl4D4',
    'container.build_id' => '26e39c28',
    'container.build_time' => 1551187942,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZySl4D4');
