<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKHFxDgE\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKHFxDgE/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKHFxDgE.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKHFxDgE\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerKHFxDgE\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'KHFxDgE',
    'container.build_id' => 'cba66ec5',
    'container.build_time' => 1551185405,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKHFxDgE');
