<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKG8p3Ns\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKG8p3Ns/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKG8p3Ns.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKG8p3Ns\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerKG8p3Ns\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'KG8p3Ns',
    'container.build_id' => 'a3708a2a',
    'container.build_time' => 1551259917,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKG8p3Ns');
